import { Card } from '@/.expo/types/card';

export const INITIAL_DECK: Card[] = [
  { suit: 'hearts', value: 1 },
  { suit: 'hearts', value: 2 },
  { suit: 'hearts', value: 3 },
  { suit: 'hearts', value: 4 },
  { suit: 'hearts', value: 5 },
  { suit: 'hearts', value: 6 },
  { suit: 'hearts', value: 7 },
  { suit: 'hearts', value: 8 },
  { suit: 'hearts', value: 9 },
  { suit: 'hearts', value: 10 },
  { suit: 'hearts', value: 11 },
  { suit: 'hearts', value: 12 },
  { suit: 'hearts', value: 13 },
  { suit: 'diamonds', value: 1 },
  { suit: 'diamonds', value: 2 },
  { suit: 'diamonds', value: 3 },
  { suit: 'diamonds', value: 4 },
  { suit: 'diamonds', value: 5 },
  { suit: 'diamonds', value: 6 },
  { suit: 'diamonds', value: 7 },
  { suit: 'diamonds', value: 8 },
  { suit: 'diamonds', value: 9 },
  { suit: 'diamonds', value: 10 },
  { suit: 'diamonds', value: 11 },
  { suit: 'diamonds', value: 12 },
  { suit: 'diamonds', value: 13 },
  { suit: 'clubs', value: 1 },
  { suit: 'clubs', value: 2 },
  { suit: 'clubs', value: 3 },
  { suit: 'clubs', value: 4 },
  { suit: 'clubs', value: 5 },
  { suit: 'clubs', value: 6 },
  { suit: 'clubs', value: 7 },
  { suit: 'clubs', value: 8 },
  { suit: 'clubs', value: 9 },
  { suit: 'clubs', value: 10 },
  { suit: 'clubs', value: 11 },
  { suit: 'clubs', value: 12 },
  { suit: 'clubs', value: 13 },
  { suit: 'spades', value: 1 },
  { suit: 'spades', value: 2 },
  { suit: 'spades', value: 3 },
  { suit: 'spades', value: 4 },
  { suit: 'spades', value: 5 },
  { suit: 'spades', value: 6 },
  { suit: 'spades', value: 7 },
  { suit: 'spades', value: 8 },
  { suit: 'spades', value: 9 },
  { suit: 'spades', value: 10 },
  { suit: 'spades', value: 11 },
  { suit: 'spades', value: 12 },
  { suit: 'spades', value: 13 },
] as const;

export const GAME_CONSTANTS = {
    STARTING_HAND_SIZE: 5,
    MAX_DISCARD_PER_TURN: 3,
    ROUND_STARTING_SCORE: 100,
    DEFAULT_GAME_MODE: 'normal',
  // Playthrough tunables
  STARTING_CASH: 300,
  HANDS_PER_BLIND: 5, // number of playable hands per blind
  MAX_ANTE: 8, // completing ante 8 counts as a win
  BASE_TARGET_CHIPS: 300, // base target chips for Ante 1 Small Blind
  ANTE_SCALE: 1.6, // multiplicative scale per ante
  BLIND_MULTIPLIERS: {
    small: 1.0,
    big: 1.5,
    boss: 2.2,
  } as const,
  // Overflow guard (soft cap)
  MAX_SAFE_TARGET: Number.MAX_SAFE_INTEGER,
} as const;
